version: '2.12.2'

services:

  # api:
  #   build: 
  #     dockerfile: Dockerfile
  #     context: .
  #     target: development
  #   restart: always
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #     - .env
  #   command: 
  #     # - npx prisma migrate dev
  #     - npm run start:dev
  #   ports:
  #     - 3001:3001

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: pingip
    ports:
      - '5432:5432'