version: '2.12.2'

services:

  api-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/nestapp
      - /nestapp/node_modules
    env_file:
      - .env
    tty: true
    ports:
      - ${DOCKER_APP_PORT}:3000
      
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: pingip
    ports:
      - '${DOCKER_POSTGRESS_PORT}:5432'